oss:
  bucket_name: 'bucket_name'
  endpoint: 'endpoint'
  fast_endpoint: 'fast_endpoint'
  access_key: 'access_key'
  access_key_secret: 'access_key_secret'
mail:
  smtp: 'smtp'
  port: 'port'
  user: 'user'
  password: 'password'
notice_mail: 
  - 'notice_mail'
tg:
  key: 'key'
tg_chat_id: 'tg_chat_id'
back_path: 'xxxx/path'
corn:
  backup_task: '0 25 0 * * ?'
  liveness: '0 0 0 * * ?'
id: ''