oss:
  bucket_name: 'bucket_name'
  endpoint: 'endpoint'
  fast_endpoint: 'fast_endpoint'
  access_key: 'access_key'
  access_key_secret: 'access_key_secret'
tg_key: 'tg_key'
tg_chat_id: 'tg_chat_id'
back_path: 'xxxx/path'