oss:
  bucket_name: 'bucket_name'
  endpoint: 'endpoint'
  fast_endpoint: 'fast_endpoint'
  access_key: 'access_key'
  access_key_secret: 'access_key_secret'
mail:
  smtp: smtp.xxx.com
  port: 465
  user: sender@mail.com
  password: pw
notice_mail: 'notice_mail@mail.com'
back_path: 'xxxx/path'